language: java
jdk:
  - openjdk11
addons:
  sonarcloud:
    organization: "fmake-org"
    token:
      secure: $SONAR_TOKEN
script:
  - ./gradlew assemble
  - ./gradlew jacocoTestReport
  - sonar-scanner